language: python

python:
  - "3.6.3"

before_install:
  # Here we just install Miniconda, which you shouldn't have to change.
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda

install:
  - conda env create --yes -f environment.yml
  - source activate taylor-pruning
  - pip install .

script:
  - pytest